server:
  port: 5678

spring:
  application:
    name: mimi-rental

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.101.231.98:3306/mimi?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
#      ddl-auto: none
      ddl-auto: update


    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
